Need to redifine the main function in url_fopen, but unsure of how
kiaras-mbp:C++ kiararey$ g++ -std=c++0x -o straw main.cpp straw.cpp  -lcurl -lz
main.cpp:31:5: error: redefinition of 'main'
int main(int argc, char *argv[])
    ^
./url_fopen.cpp:456:5: note: previous definition is here
int main(int argc, char *argv[])
    ^
1 error generated.
kiaras-mbp:C++ kiararey$